server:
    port: 8083
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: pravin
      clientSecret: pravin123
      accessTokenUri: http://localhost:8080/sso/oauth/token
      userAuthorizationUri: http://localhost:8080/sso/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/sso/user

